name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install upx
        run: bash -c "curl -L https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz > /tmp/upx.tar.xz; tar xvf /tmp/upx.tar.xz -C /tmp/; sudo mv /tmp/upx-4.2.4-amd64_linux/upx /usr/bin"
        # upx from repository is too old (3.x), not working on mips
        # run: sudo apt install upx -y

      - uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自動で生成されるシークレット
